# services = vull que em egneri contenidor amb nom postgres amb el Dockerfile
# exportes a port 5432 en el nostre ordinador
# vols que la variable de imatge. 
# per executarho vas a una terminal i fas: docker compose up

version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repte_insdo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./init-data:/docker-entrypoint-initdb.d
