version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repte_insdo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./init-data:/docker-entrypoint-initdb.d
